# AUTOGENERATED! DO NOT EDIT! File to edit: DataPipelineNotebooks/ParseGFSBatch.ipynb (unless otherwise specified).

__all__ = ['ParseGFSBatch']

# Cell
class ParseGFSBatch(ParseGFS):
    """
    """

    def __init__(self, season, state, data_root, interpolate=1):
        super().__init__(season, state, data_root, interpolate)

