//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;
namespace GetData
{
    // 
    // This source code was auto-generated by xsd, Version=4.8.3928.0.
    // 


    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://caaml.org/Schemas/V5.0/Profiles/BulletinCAC")]
    [System.Xml.Serialization.XmlRootAttribute("CaamlData", Namespace = "http://caaml.org/Schemas/V5.0/Profiles/BulletinCAC", IsNullable = false)]
    public partial class CaamlDataType
    {

        private CaamlDataTypeMetaDataProperty metaDataPropertyField;

        private aspects aspectsField;

        private elevations elevationsField;

        private CaamlDataTypeObservations observationsField;

        /// <remarks/>
        public CaamlDataTypeMetaDataProperty metaDataProperty
        {
            get
            {
                return this.metaDataPropertyField;
            }
            set
            {
                this.metaDataPropertyField = value;
            }
        }

        /// <remarks/>
        public aspects aspects
        {
            get
            {
                return this.aspectsField;
            }
            set
            {
                this.aspectsField = value;
            }
        }

        /// <remarks/>
        public elevations elevations
        {
            get
            {
                return this.elevationsField;
            }
            set
            {
                this.elevationsField = value;
            }
        }

        /// <remarks/>
        public CaamlDataTypeObservations observations
        {
            get
            {
                return this.observationsField;
            }
            set
            {
                this.observationsField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://caaml.org/Schemas/V5.0/Profiles/BulletinCAC")]
    public partial class CaamlDataTypeMetaDataProperty
    {

        private MetaDataType metaDataField;

        /// <remarks/>
        public MetaDataType MetaData
        {
            get
            {
                return this.metaDataField;
            }
            set
            {
                this.metaDataField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://caaml.org/Schemas/V5.0/Profiles/BulletinCAC")]
    public partial class MetaDataType
    {

        private TimePositionType dateTimeReportField;

        private SourceRefType srcRefField;

        private string srcURLField;

        private MetaDataTypeLanguage languageField;

        private string commentField;

        private System.Xml.XmlElement customDataField;

        /// <remarks/>
        public TimePositionType dateTimeReport
        {
            get
            {
                return this.dateTimeReportField;
            }
            set
            {
                this.dateTimeReportField = value;
            }
        }

        /// <remarks/>
        public SourceRefType srcRef
        {
            get
            {
                return this.srcRefField;
            }
            set
            {
                this.srcRefField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "anyURI")]
        public string srcURL
        {
            get
            {
                return this.srcURLField;
            }
            set
            {
                this.srcURLField = value;
            }
        }

        /// <remarks/>
        public MetaDataTypeLanguage language
        {
            get
            {
                return this.languageField;
            }
            set
            {
                this.languageField = value;
            }
        }

        /// <remarks/>
        public string comment
        {
            get
            {
                return this.commentField;
            }
            set
            {
                this.commentField = value;
            }
        }

        /// <remarks/>
        public System.Xml.XmlElement customData
        {
            get
            {
                return this.customDataField;
            }
            set
            {
                this.customDataField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.opengis.net/gml")]
    public partial class TimePositionType
    {

        private string valueField;

        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://caaml.org/Schemas/V5.0/Profiles/BulletinCAC")]
    public partial class WindSpeedType
    {

        private UomSpeedType uomField;

        private string valueField;

        public WindSpeedType()
        {
            this.uomField = UomSpeedType.na;
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public UomSpeedType uom
        {
            get
            {
                return this.uomField;
            }
            set
            {
                this.uomField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://caaml.org/Schemas/V5.0/Profiles/BulletinCAC")]
    public enum UomSpeedType
    {

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("kmh-1")]
        kmh1,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("ms-1")]
        ms1,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("mi/h")]
        mih,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("n/a")]
        na,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://caaml.org/Schemas/V5.0/Profiles/BulletinCAC")]
    public partial class WindObsType
    {

        private WindObsTypeComponents componentsField;

        /// <remarks/>
        public WindObsTypeComponents Components
        {
            get
            {
                return this.componentsField;
            }
            set
            {
                this.componentsField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://caaml.org/Schemas/V5.0/Profiles/BulletinCAC")]
    public partial class WindObsTypeComponents
    {

        private WindSpeedType speedField;

        private string directionField;

        /// <remarks/>
        public WindSpeedType speed
        {
            get
            {
                return this.speedField;
            }
            set
            {
                this.speedField = value;
            }
        }

        /// <remarks/>
        public string direction
        {
            get
            {
                return this.directionField;
            }
            set
            {
                this.directionField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://caaml.org/Schemas/V5.0/Profiles/BulletinCAC")]
    public partial class DensityMeasComponentsType
    {

        private DensityMeasComponentsTypeSnowHeight snowHeightField;

        /// <remarks/>
        public DensityMeasComponentsTypeSnowHeight snowHeight
        {
            get
            {
                return this.snowHeightField;
            }
            set
            {
                this.snowHeightField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://caaml.org/Schemas/V5.0/Profiles/BulletinCAC")]
    public partial class DensityMeasComponentsTypeSnowHeight
    {

        private UomLengthMedType uomField;

        private string valueField;

        public DensityMeasComponentsTypeSnowHeight()
        {
            this.uomField = UomLengthMedType.cm;
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public UomLengthMedType uom
        {
            get
            {
                return this.uomField;
            }
            set
            {
                this.uomField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://caaml.org/Schemas/V5.0/Profiles/BulletinCAC")]
    public enum UomLengthMedType
    {

        /// <remarks/>
        cm,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://caaml.org/Schemas/V5.0/Profiles/BulletinCAC")]
    public partial class SnowHeightPointRegularType
    {

        private DensityMeasComponentsType componentsField;

        /// <remarks/>
        public DensityMeasComponentsType Components
        {
            get
            {
                return this.componentsField;
            }
            set
            {
                this.componentsField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://caaml.org/Schemas/V5.0/Profiles/BulletinCAC")]
    public partial class TempType
    {

        private UomTempType uomField;

        private string valueField;

        public TempType()
        {
            this.uomField = UomTempType.degC;
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public UomTempType uom
        {
            get
            {
                return this.uomField;
            }
            set
            {
                this.uomField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://caaml.org/Schemas/V5.0/Profiles/BulletinCAC")]
    public enum UomTempType
    {

        /// <remarks/>
        degC,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://caaml.org/Schemas/V5.0/Profiles/BulletinCAC")]
    public partial class GrainSizeType
    {

        private GrainSizeTypeComponents componentsField;

        private UomLengthType uomField;

        public GrainSizeType()
        {
            this.uomField = UomLengthType.mm;
        }

        /// <remarks/>
        public GrainSizeTypeComponents Components
        {
            get
            {
                return this.componentsField;
            }
            set
            {
                this.componentsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public UomLengthType uom
        {
            get
            {
                return this.uomField;
            }
            set
            {
                this.uomField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://caaml.org/Schemas/V5.0/Profiles/BulletinCAC")]
    public partial class GrainSizeTypeComponents
    {

        private string avgField;

        private string avgMaxField;

        /// <remarks/>
        public string avg
        {
            get
            {
                return this.avgField;
            }
            set
            {
                this.avgField = value;
            }
        }

        /// <remarks/>
        public string avgMax
        {
            get
            {
                return this.avgMaxField;
            }
            set
            {
                this.avgMaxField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://caaml.org/Schemas/V5.0/Profiles/BulletinCAC")]
    public enum UomLengthType
    {

        /// <remarks/>
        cm,

        /// <remarks/>
        mm,

        /// <remarks/>
        m,

        /// <remarks/>
        @in,

        /// <remarks/>
        ft,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://caaml.org/Schemas/V5.0/Profiles/BulletinCAC")]
    public partial class MeasureLengthCmType
    {

        private UomLengthType uomField;

        private string valueField;

        public MeasureLengthCmType()
        {
            this.uomField = UomLengthType.cm;
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public UomLengthType uom
        {
            get
            {
                return this.uomField;
            }
            set
            {
                this.uomField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://caaml.org/Schemas/V5.0/Profiles/BulletinCAC")]
    public partial class LayerPointObsMetaDataType
    {

        private System.Xml.XmlElement customDataField;

        /// <remarks/>
        public System.Xml.XmlElement customData
        {
            get
            {
                return this.customDataField;
            }
            set
            {
                this.customDataField = value;
            }
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(LayerBaseType))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://caaml.org/Schemas/V5.0/Profiles/BulletinCAC")]
    public partial class LayerPointObsRootType
    {

        private LayerPointObsRootTypeMetaDataProperty metaDataPropertyField;

        private string commentField;

        private System.Xml.XmlElement customDataField;

        private string idField;

        /// <remarks/>
        public LayerPointObsRootTypeMetaDataProperty metaDataProperty
        {
            get
            {
                return this.metaDataPropertyField;
            }
            set
            {
                this.metaDataPropertyField = value;
            }
        }

        /// <remarks/>
        public string comment
        {
            get
            {
                return this.commentField;
            }
            set
            {
                this.commentField = value;
            }
        }

        /// <remarks/>
        public System.Xml.XmlElement customData
        {
            get
            {
                return this.customDataField;
            }
            set
            {
                this.customDataField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Form = System.Xml.Schema.XmlSchemaForm.Qualified, Namespace = "http://www.opengis.net/gml", DataType = "ID")]
        public string id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://caaml.org/Schemas/V5.0/Profiles/BulletinCAC")]
    public partial class LayerPointObsRootTypeMetaDataProperty
    {

        private LayerPointObsMetaDataType metaDataField;

        /// <remarks/>
        public LayerPointObsMetaDataType MetaData
        {
            get
            {
                return this.metaDataField;
            }
            set
            {
                this.metaDataField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://caaml.org/Schemas/V5.0/Profiles/BulletinCAC")]
    public partial class LayerBaseType : LayerPointObsRootType
    {

        private MeasureLengthCmType depthTopField;

        private MeasureLengthCmType thicknessField;

        private string grainFormPrimaryField;

        private string grainFormSecondaryField;

        private GrainSizeType grainSizeField;

        private ValidTimeType validFormationTimeField;

        /// <remarks/>
        public MeasureLengthCmType depthTop
        {
            get
            {
                return this.depthTopField;
            }
            set
            {
                this.depthTopField = value;
            }
        }

        /// <remarks/>
        public MeasureLengthCmType thickness
        {
            get
            {
                return this.thicknessField;
            }
            set
            {
                this.thicknessField = value;
            }
        }

        /// <remarks/>
        public string grainFormPrimary
        {
            get
            {
                return this.grainFormPrimaryField;
            }
            set
            {
                this.grainFormPrimaryField = value;
            }
        }

        /// <remarks/>
        public string grainFormSecondary
        {
            get
            {
                return this.grainFormSecondaryField;
            }
            set
            {
                this.grainFormSecondaryField = value;
            }
        }

        /// <remarks/>
        public GrainSizeType grainSize
        {
            get
            {
                return this.grainSizeField;
            }
            set
            {
                this.grainSizeField = value;
            }
        }

        /// <remarks/>
        public ValidTimeType validFormationTime
        {
            get
            {
                return this.validFormationTimeField;
            }
            set
            {
                this.validFormationTimeField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://caaml.org/Schemas/V5.0/Profiles/BulletinCAC")]
    [System.Xml.Serialization.XmlRootAttribute("validTime", Namespace = "http://caaml.org/Schemas/V5.0/Profiles/BulletinCAC", IsNullable = false)]
    public partial class ValidTimeType
    {

        private object itemField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("TimeInstant", typeof(TimeInstantType))]
        [System.Xml.Serialization.XmlElementAttribute("TimePeriod", typeof(TimePeriodType))]
        public object Item
        {
            get
            {
                return this.itemField;
            }
            set
            {
                this.itemField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://caaml.org/Schemas/V5.0/Profiles/BulletinCAC")]
    [System.Xml.Serialization.XmlRootAttribute("TimeInstant", Namespace = "http://caaml.org/Schemas/V5.0/Profiles/BulletinCAC", IsNullable = false)]
    public partial class TimeInstantType
    {

        private TimePositionType timePositionField;

        private string idField;

        /// <remarks/>
        public TimePositionType timePosition
        {
            get
            {
                return this.timePositionField;
            }
            set
            {
                this.timePositionField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Form = System.Xml.Schema.XmlSchemaForm.Qualified, Namespace = "http://www.opengis.net/gml", DataType = "ID")]
        public string id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://caaml.org/Schemas/V5.0/Profiles/BulletinCAC")]
    [System.Xml.Serialization.XmlRootAttribute("TimePeriod", Namespace = "http://caaml.org/Schemas/V5.0/Profiles/BulletinCAC", IsNullable = false)]
    public partial class TimePeriodType
    {

        private TimePositionType beginPositionField;

        private TimePositionType endPositionField;

        private string idField;

        /// <remarks/>
        public TimePositionType beginPosition
        {
            get
            {
                return this.beginPositionField;
            }
            set
            {
                this.beginPositionField = value;
            }
        }

        /// <remarks/>
        public TimePositionType endPosition
        {
            get
            {
                return this.endPositionField;
            }
            set
            {
                this.endPositionField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Form = System.Xml.Schema.XmlSchemaForm.Qualified, Namespace = "http://www.opengis.net/gml", DataType = "ID")]
        public string id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://caaml.org/Schemas/V5.0/Profiles/BulletinCAC")]
    public partial class AvProblemType
    {

        private AvProblemTypeType typeField;

        private ValidAspectType[] validAspectField;

        private ValidElevationType[] validElevationField;

        private AvProblemTypeExpectedAvSize expectedAvSizeField;

        private AvProblemTypeLikelihoodOfTriggering likelihoodOfTriggeringField;

        private string travelAdvisoryCommentField;

        private string commentField;

        private System.Xml.XmlElement customDataField;

        /// <remarks/>
        public AvProblemTypeType type
        {
            get
            {
                return this.typeField;
            }
            set
            {
                this.typeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("validAspect")]
        public ValidAspectType[] validAspect
        {
            get
            {
                return this.validAspectField;
            }
            set
            {
                this.validAspectField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("validElevation")]
        public ValidElevationType[] validElevation
        {
            get
            {
                return this.validElevationField;
            }
            set
            {
                this.validElevationField = value;
            }
        }

        /// <remarks/>
        public AvProblemTypeExpectedAvSize expectedAvSize
        {
            get
            {
                return this.expectedAvSizeField;
            }
            set
            {
                this.expectedAvSizeField = value;
            }
        }

        /// <remarks/>
        public AvProblemTypeLikelihoodOfTriggering likelihoodOfTriggering
        {
            get
            {
                return this.likelihoodOfTriggeringField;
            }
            set
            {
                this.likelihoodOfTriggeringField = value;
            }
        }

        /// <remarks/>
        public string travelAdvisoryComment
        {
            get
            {
                return this.travelAdvisoryCommentField;
            }
            set
            {
                this.travelAdvisoryCommentField = value;
            }
        }

        /// <remarks/>
        public string comment
        {
            get
            {
                return this.commentField;
            }
            set
            {
                this.commentField = value;
            }
        }

        /// <remarks/>
        public System.Xml.XmlElement customData
        {
            get
            {
                return this.customDataField;
            }
            set
            {
                this.customDataField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://caaml.org/Schemas/V5.0/Profiles/BulletinCAC")]
    public enum AvProblemTypeType
    {

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Loose Dry")]
        LooseDry,
        
        //weirdly this invlid value is showing up in some forecasts
        [System.Xml.Serialization.XmlEnumAttribute("Dry Loose")]
        DryLoose,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Loose Wet")]
        LooseWet,
        
        //weirdly this invlid value is showing up in some forecasts
        [System.Xml.Serialization.XmlEnumAttribute("Wet Loose")]
        WetLoose,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Wind Slabs")]
        WindSlabs,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Storm Slabs")]
        StormSlabs,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Wet Slabs")]
        WetSlabs,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Persistent Slabs")]
        PersistentSlabs,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Deep Persistent Slabs")]
        DeepPersistentSlabs,

        /// <remarks/>
        Cornices,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Avalanches de neige sèche sans cohésion")]
        Avalanchesdeneigesèchesanscohésion,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Avalanches de neige mouillée sans cohésion")]
        Avalanchesdeneigemouilléesanscohésion,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Avalanches de plaques à vent")]
        Avalanchesdeplaquesàvent,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Avalanches de plaques de neige de tempête")]
        Avalanchesdeplaquesdeneigedetempête,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Avalanches de plaques de neige mouillée")]
        Avalanchesdeplaquesdeneigemouillée,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Avalanches de plaques persistantes")]
        Avalanchesdeplaquespersistantes,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Avalanches de plaques profondes persistantes")]
        Avalanchesdeplaquesprofondespersistantes,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Avalanches de corniches")]
        Avalanchesdecorniches,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://caaml.org/Schemas/V5.0/Profiles/BulletinCAC")]
    [System.Xml.Serialization.XmlRootAttribute("validAspect", Namespace = "http://caaml.org/Schemas/V5.0/Profiles/BulletinCAC", IsNullable = false)]
    public partial class ValidAspectType
    {

        private string hrefField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Form = System.Xml.Schema.XmlSchemaForm.Qualified, Namespace = "http://www.w3.org/1999/xlink", DataType = "anyURI")]
        public string href
        {
            get
            {
                return this.hrefField;
            }
            set
            {
                this.hrefField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://caaml.org/Schemas/V5.0/Profiles/BulletinCAC")]
    [System.Xml.Serialization.XmlRootAttribute("validElevation", Namespace = "http://caaml.org/Schemas/V5.0/Profiles/BulletinCAC", IsNullable = false)]
    public partial class ValidElevationType
    {

        private string hrefField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Form = System.Xml.Schema.XmlSchemaForm.Qualified, Namespace = "http://www.w3.org/1999/xlink", DataType = "anyURI")]
        public string href
        {
            get
            {
                return this.hrefField;
            }
            set
            {
                this.hrefField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://caaml.org/Schemas/V5.0/Profiles/BulletinCAC")]
    public partial class AvProblemTypeExpectedAvSize
    {

        private AvProblemTypeExpectedAvSizeValues valuesField;

        /// <remarks/>
        public AvProblemTypeExpectedAvSizeValues Values
        {
            get
            {
                return this.valuesField;
            }
            set
            {
                this.valuesField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://caaml.org/Schemas/V5.0/Profiles/BulletinCAC")]
    public partial class AvProblemTypeExpectedAvSizeValues
    {

        private ExpectedAvSizeValueType minField;

        private ExpectedAvSizeValueType typicalField;

        private ExpectedAvSizeValueType maxField;

        /// <remarks/>
        public ExpectedAvSizeValueType min
        {
            get
            {
                return this.minField;
            }
            set
            {
                this.minField = value;
            }
        }

        /// <remarks/>
        public ExpectedAvSizeValueType typical
        {
            get
            {
                return this.typicalField;
            }
            set
            {
                this.typicalField = value;
            }
        }

        /// <remarks/>
        public ExpectedAvSizeValueType max
        {
            get
            {
                return this.maxField;
            }
            set
            {
                this.maxField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://caaml.org/Schemas/V5.0/Profiles/BulletinCAC")]
    public enum ExpectedAvSizeValueType
    {

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("0.5")]
        Item05,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1.0")]
        Item10,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1.5")]
        Item15,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("2.0")]
        Item20,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("2.5")]
        Item25,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("3.0")]
        Item30,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("3.5")]
        Item35,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("4.0")]
        Item40,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("4.5")]
        Item45,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("5.0")]
        Item50,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://caaml.org/Schemas/V5.0/Profiles/BulletinCAC")]
    public partial class AvProblemTypeLikelihoodOfTriggering
    {

        private AvProblemTypeLikelihoodOfTriggeringValues valuesField;

        /// <remarks/>
        public AvProblemTypeLikelihoodOfTriggeringValues Values
        {
            get
            {
                return this.valuesField;
            }
            set
            {
                this.valuesField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://caaml.org/Schemas/V5.0/Profiles/BulletinCAC")]
    public partial class AvProblemTypeLikelihoodOfTriggeringValues
    {

        private LikelihoodOfTriggeringValueType minField;

        private LikelihoodOfTriggeringValueType typicalField;

        private LikelihoodOfTriggeringValueType maxField;

        /// <remarks/>
        public LikelihoodOfTriggeringValueType min
        {
            get
            {
                return this.minField;
            }
            set
            {
                this.minField = value;
            }
        }

        /// <remarks/>
        public LikelihoodOfTriggeringValueType typical
        {
            get
            {
                return this.typicalField;
            }
            set
            {
                this.typicalField = value;
            }
        }

        /// <remarks/>
        public LikelihoodOfTriggeringValueType max
        {
            get
            {
                return this.maxField;
            }
            set
            {
                this.maxField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://caaml.org/Schemas/V5.0/Profiles/BulletinCAC")]
    public enum LikelihoodOfTriggeringValueType
    {

        /// <remarks/>
        Certain,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Certain - Very Likely")]
        CertainVeryLikely,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Very Likely")]
        VeryLikely,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Very Likely - Likely")]
        VeryLikelyLikely,

        /// <remarks/>
        Likely,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Likely - Possible")]
        LikelyPossible,

        /// <remarks/>
        Possible,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Possible - Unlikely")]
        PossibleUnlikely,

        /// <remarks/>
        Unlikely,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Certain - Très probable")]
        CertainTrèsprobable,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Très probable")]
        Trèsprobable,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Très probable - Probable")]
        TrèsprobableProbable,

        /// <remarks/>
        Probable,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Probable - Possible")]
        ProbablePossible,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Possible")]
        Possible1,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Possible - Improbable")]
        PossibleImprobable,

        /// <remarks/>
        Improbable,
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(WxObsMeasurementsType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SpawMeasurementsType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(BulletinMeasurementsType))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://caaml.org/Schemas/V5.0/Profiles/BulletinCAC")]
    public abstract partial class AbstractObsMeasurementsType
    {

        private System.Xml.XmlElement customDataField;

        private string commentField;

        private string highlightsField;

        /// <remarks/>
        public System.Xml.XmlElement customData
        {
            get
            {
                return this.customDataField;
            }
            set
            {
                this.customDataField = value;
            }
        }

        /// <remarks/>
        public string comment
        {
            get
            {
                return this.commentField;
            }
            set
            {
                this.commentField = value;
            }
        }

        /// <remarks/>
        public string highlights
        {
            get
            {
                return this.highlightsField;
            }
            set
            {
                this.highlightsField = value;
            }
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SpawType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(WxObsType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(BulletinType))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://caaml.org/Schemas/V5.0/Profiles/BulletinCAC")]
    public abstract partial class AbstractObservationType
    {

        private System.Xml.XmlElement customDataField;

        private ValidTimeType validTimeField;

        private string idField;

        /// <remarks/>
        public System.Xml.XmlElement customData
        {
            get
            {
                return this.customDataField;
            }
            set
            {
                this.customDataField = value;
            }
        }

        /// <remarks/>
        public ValidTimeType validTime
        {
            get
            {
                return this.validTimeField;
            }
            set
            {
                this.validTimeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Form = System.Xml.Schema.XmlSchemaForm.Qualified, Namespace = "http://www.opengis.net/gml", DataType = "ID")]
        public string id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://caaml.org/Schemas/V5.0/Profiles/BulletinCAC")]
    public partial class ElevationLabelType
    {

        private ElevationLabelTypeDescription descriptionField;

        private System.Xml.XmlElement customDataField;

        private string idField;

        /// <remarks/>
        public ElevationLabelTypeDescription description
        {
            get
            {
                return this.descriptionField;
            }
            set
            {
                this.descriptionField = value;
            }
        }

        /// <remarks/>
        public System.Xml.XmlElement customData
        {
            get
            {
                return this.customDataField;
            }
            set
            {
                this.customDataField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Form = System.Xml.Schema.XmlSchemaForm.Qualified, Namespace = "http://www.opengis.net/gml", DataType = "ID")]
        public string id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://caaml.org/Schemas/V5.0/Profiles/BulletinCAC")]
    public enum ElevationLabelTypeDescription
    {

        /// <remarks/>
        Alpine,

        /// <remarks/>
        Treeline,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Below Treeline")]
        BelowTreeline,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Zone Alpine")]
        ZoneAlpine,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Limite Forestière")]
        LimiteForestière,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Au-dessous de la limite forestière")]
        Audessousdelalimiteforestière,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://caaml.org/Schemas/V5.0/Profiles/BulletinCAC")]
    public partial class AspectRangeType
    {

        private string beginPositionField;

        private string endPositionField;

        private System.Xml.XmlElement customDataField;

        private string idField;

        /// <remarks/>
        public string beginPosition
        {
            get
            {
                return this.beginPositionField;
            }
            set
            {
                this.beginPositionField = value;
            }
        }

        /// <remarks/>
        public string endPosition
        {
            get
            {
                return this.endPositionField;
            }
            set
            {
                this.endPositionField = value;
            }
        }

        /// <remarks/>
        public System.Xml.XmlElement customData
        {
            get
            {
                return this.customDataField;
            }
            set
            {
                this.customDataField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Form = System.Xml.Schema.XmlSchemaForm.Qualified, Namespace = "http://www.opengis.net/gml", DataType = "ID")]
        public string id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://caaml.org/Schemas/V5.0/Profiles/BulletinCAC")]
    public partial class PersonRefType
    {

        private PersonType itemField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Person")]
        public PersonType Item
        {
            get
            {
                return this.itemField;
            }
            set
            {
                this.itemField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://caaml.org/Schemas/V5.0/Profiles/BulletinCAC")]
    [System.Xml.Serialization.XmlRootAttribute("Person", Namespace = "http://caaml.org/Schemas/V5.0/Profiles/BulletinCAC", IsNullable = false)]
    public partial class PersonType : SourceType
    {
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(PersonType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(OperationType))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://caaml.org/Schemas/V5.0/Profiles/BulletinCAC")]
    public partial class SourceType
    {

        private System.Xml.XmlElement customDataField;

        private string nameField;

        private string idField;

        /// <remarks/>
        public System.Xml.XmlElement customData
        {
            get
            {
                return this.customDataField;
            }
            set
            {
                this.customDataField = value;
            }
        }

        /// <remarks/>
        public string name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Form = System.Xml.Schema.XmlSchemaForm.Qualified, Namespace = "http://www.opengis.net/gml", DataType = "ID")]
        public string id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://caaml.org/Schemas/V5.0/Profiles/BulletinCAC")]
    public partial class SourceRefType
    {

        private OperationType itemField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Operation")]
        public OperationType Item
        {
            get
            {
                return this.itemField;
            }
            set
            {
                this.itemField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://caaml.org/Schemas/V5.0/Profiles/BulletinCAC")]
    [System.Xml.Serialization.XmlRootAttribute("Operation", Namespace = "http://caaml.org/Schemas/V5.0/Profiles/BulletinCAC", IsNullable = false)]
    public partial class OperationType : SourceType
    {

        private PersonRefType[] contactPersonField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("contactPerson")]
        public PersonRefType[] contactPerson
        {
            get
            {
                return this.contactPersonField;
            }
            set
            {
                this.contactPersonField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://caaml.org/Schemas/V5.0/Profiles/BulletinCAC")]
    public enum MetaDataTypeLanguage
    {

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("en-CA")]
        enCA,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("fr-CA")]
        frCA,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://caaml.org/Schemas/V5.0/Profiles/BulletinCAC")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://caaml.org/Schemas/V5.0/Profiles/BulletinCAC", IsNullable = false)]
    public partial class aspects
    {

        private AspectRangeType[] itemsField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("AspectRange")]
        public AspectRangeType[] Items
        {
            get
            {
                return this.itemsField;
            }
            set
            {
                this.itemsField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://caaml.org/Schemas/V5.0/Profiles/BulletinCAC")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://caaml.org/Schemas/V5.0/Profiles/BulletinCAC", IsNullable = false)]
    public partial class elevations
    {

        private ElevationLabelType[] itemsField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ElevationLabel")]
        public ElevationLabelType[] Items
        {
            get
            {
                return this.itemsField;
            }
            set
            {
                this.itemsField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://caaml.org/Schemas/V5.0/Profiles/BulletinCAC")]
    public partial class CaamlDataTypeObservations
    {

        private AbstractObservationType itemField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Bulletin", typeof(BulletinType))]
        [System.Xml.Serialization.XmlElementAttribute("Spaw", typeof(SpawType))]
        public AbstractObservationType Item
        {
            get
            {
                return this.itemField;
            }
            set
            {
                this.itemField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://caaml.org/Schemas/V5.0/Profiles/BulletinCAC")]
    [System.Xml.Serialization.XmlRootAttribute("Bulletin", Namespace = "http://caaml.org/Schemas/V5.0/Profiles/BulletinCAC", IsNullable = false)]
    public partial class BulletinType : AbstractObservationType
    {

        private BulletinTypeBulletinResultsOf bulletinResultsOfField;

        private BulletinTypeLocRef locRefField;

        private BulletinTypeLinkedObservations linkedObservationsField;

        /// <remarks/>
        public BulletinTypeBulletinResultsOf bulletinResultsOf
        {
            get
            {
                return this.bulletinResultsOfField;
            }
            set
            {
                this.bulletinResultsOfField = value;
            }
        }

        /// <remarks/>
        public BulletinTypeLocRef locRef
        {
            get
            {
                return this.locRefField;
            }
            set
            {
                this.locRefField = value;
            }
        }

        /// <remarks/>
        public BulletinTypeLinkedObservations linkedObservations
        {
            get
            {
                return this.linkedObservationsField;
            }
            set
            {
                this.linkedObservationsField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://caaml.org/Schemas/V5.0/Profiles/BulletinCAC")]
    public partial class BulletinTypeBulletinResultsOf
    {

        private BulletinMeasurementsType bulletinMeasurementsField;

        /// <remarks/>
        public BulletinMeasurementsType BulletinMeasurements
        {
            get
            {
                return this.bulletinMeasurementsField;
            }
            set
            {
                this.bulletinMeasurementsField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://caaml.org/Schemas/V5.0/Profiles/BulletinCAC")]
    [System.Xml.Serialization.XmlRootAttribute("BulletinMeasurements", Namespace = "http://caaml.org/Schemas/V5.0/Profiles/BulletinCAC", IsNullable = false)]
    public partial class BulletinMeasurementsType : AbstractObsMeasurementsType
    {

        private string bulletinTitleField;

        private BulletinMeasurementsTypeBulletinConfidence bulletinConfidenceField;

        private BulletinMeasurementsTypeDangerMode dangerModeField;

        private bool dangerModeFieldSpecified;

        private DangerRatingsTypeDangerRating[] dangerRatingsField;

        private BulletinMeasurementsTypeAvProblems avProblemsField;

        private BulletinMeasurementsTypePWLs pWLsField;

        private string wxSynopsisCommentField;

        private string avActivityCommentField;

        private string snowpackStructureCommentField;

        private string travelAdvisoryCommentField;

        /// <remarks/>
        public string bulletinTitle
        {
            get
            {
                return this.bulletinTitleField;
            }
            set
            {
                this.bulletinTitleField = value;
            }
        }

        /// <remarks/>
        public BulletinMeasurementsTypeBulletinConfidence bulletinConfidence
        {
            get
            {
                return this.bulletinConfidenceField;
            }
            set
            {
                this.bulletinConfidenceField = value;
            }
        }

        /// <remarks/>
        public BulletinMeasurementsTypeDangerMode dangerMode
        {
            get
            {
                return this.dangerModeField;
            }
            set
            {
                this.dangerModeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool dangerModeSpecified
        {
            get
            {
                return this.dangerModeFieldSpecified;
            }
            set
            {
                this.dangerModeFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("DangerRating", IsNullable = false)]
        public DangerRatingsTypeDangerRating[] dangerRatings
        {
            get
            {
                return this.dangerRatingsField;
            }
            set
            {
                this.dangerRatingsField = value;
            }
        }

        /// <remarks/>
        public BulletinMeasurementsTypeAvProblems avProblems
        {
            get
            {
                return this.avProblemsField;
            }
            set
            {
                this.avProblemsField = value;
            }
        }

        /// <remarks/>
        public BulletinMeasurementsTypePWLs pWLs
        {
            get
            {
                return this.pWLsField;
            }
            set
            {
                this.pWLsField = value;
            }
        }

        /// <remarks/>
        public string wxSynopsisComment
        {
            get
            {
                return this.wxSynopsisCommentField;
            }
            set
            {
                this.wxSynopsisCommentField = value;
            }
        }

        /// <remarks/>
        public string avActivityComment
        {
            get
            {
                return this.avActivityCommentField;
            }
            set
            {
                this.avActivityCommentField = value;
            }
        }

        /// <remarks/>
        public string snowpackStructureComment
        {
            get
            {
                return this.snowpackStructureCommentField;
            }
            set
            {
                this.snowpackStructureCommentField = value;
            }
        }

        /// <remarks/>
        public string travelAdvisoryComment
        {
            get
            {
                return this.travelAdvisoryCommentField;
            }
            set
            {
                this.travelAdvisoryCommentField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://caaml.org/Schemas/V5.0/Profiles/BulletinCAC")]
    public partial class BulletinMeasurementsTypeBulletinConfidence
    {

        private BulletinMeasurementsTypeBulletinConfidenceComponents componentsField;

        /// <remarks/>
        public BulletinMeasurementsTypeBulletinConfidenceComponents Components
        {
            get
            {
                return this.componentsField;
            }
            set
            {
                this.componentsField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://caaml.org/Schemas/V5.0/Profiles/BulletinCAC")]
    public partial class BulletinMeasurementsTypeBulletinConfidenceComponents
    {

        private string confidenceLevelField;

        private string commentField;

        /// <remarks/>
        public string confidenceLevel
        {
            get
            {
                return this.confidenceLevelField;
            }
            set
            {
                this.confidenceLevelField = value;
            }
        }

        /// <remarks/>
        public string comment
        {
            get
            {
                return this.commentField;
            }
            set
            {
                this.commentField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://caaml.org/Schemas/V5.0/Profiles/BulletinCAC")]
    public enum BulletinMeasurementsTypeDangerMode
    {

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Early season")]
        Earlyseason,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Regular season")]
        Regularseason,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Spring situation")]
        Springsituation,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Off season")]
        Offseason,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://caaml.org/Schemas/V5.0/Profiles/BulletinCAC")]
    public partial class DangerRatingsTypeDangerRating
    {

        private LocRefType[] locRefField;

        private ValidTimeType validTimeField;

        private ValidElevationType validElevationField;

        private string mainValueField;

        private string commentField;

        private System.Xml.XmlElement customDataField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("locRef")]
        public LocRefType[] locRef
        {
            get
            {
                return this.locRefField;
            }
            set
            {
                this.locRefField = value;
            }
        }

        /// <remarks/>
        public ValidTimeType validTime
        {
            get
            {
                return this.validTimeField;
            }
            set
            {
                this.validTimeField = value;
            }
        }

        /// <remarks/>
        public ValidElevationType validElevation
        {
            get
            {
                return this.validElevationField;
            }
            set
            {
                this.validElevationField = value;
            }
        }

        /// <remarks/>
        public string mainValue
        {
            get
            {
                return this.mainValueField;
            }
            set
            {
                this.mainValueField = value;
            }
        }

        /// <remarks/>
        public string comment
        {
            get
            {
                return this.commentField;
            }
            set
            {
                this.commentField = value;
            }
        }

        /// <remarks/>
        public System.Xml.XmlElement customData
        {
            get
            {
                return this.customDataField;
            }
            set
            {
                this.customDataField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://caaml.org/Schemas/V5.0/Profiles/BulletinCAC")]
    [System.Xml.Serialization.XmlRootAttribute("locRef", Namespace = "http://caaml.org/Schemas/V5.0/Profiles/BulletinCAC", IsNullable = false)]
    public partial class LocRefType
    {

        private object itemField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("LocRefString", typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("Region", typeof(RegionType))]
        public object Item
        {
            get
            {
                return this.itemField;
            }
            set
            {
                this.itemField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://caaml.org/Schemas/V5.0/Profiles/BulletinCAC")]
    [System.Xml.Serialization.XmlRootAttribute("Region", Namespace = "http://caaml.org/Schemas/V5.0/Profiles/BulletinCAC", IsNullable = false)]
    public partial class RegionType
    {

        private string nameField;

        private string regionSubTypeField;

        private string idField;

        public RegionType()
        {
            this.regionSubTypeField = "Forecast Region";
        }

        /// <remarks/>
        public string name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }

        /// <remarks/>
        public string regionSubType
        {
            get
            {
                return this.regionSubTypeField;
            }
            set
            {
                this.regionSubTypeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Form = System.Xml.Schema.XmlSchemaForm.Qualified, Namespace = "http://www.opengis.net/gml", DataType = "ID")]
        public string id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://caaml.org/Schemas/V5.0/Profiles/BulletinCAC")]
    public partial class BulletinMeasurementsTypeAvProblems
    {

        private AvProblemType[] avProblemField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("AvProblem")]
        public AvProblemType[] AvProblem
        {
            get
            {
                return this.avProblemField;
            }
            set
            {
                this.avProblemField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://caaml.org/Schemas/V5.0/Profiles/BulletinCAC")]
    public partial class BulletinMeasurementsTypePWLs
    {

        private LayerBaseType[] pWLField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("PWL")]
        public LayerBaseType[] PWL
        {
            get
            {
                return this.pWLField;
            }
            set
            {
                this.pWLField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://caaml.org/Schemas/V5.0/Profiles/BulletinCAC")]
    public partial class BulletinTypeLocRef : LocRefType
    {
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://caaml.org/Schemas/V5.0/Profiles/BulletinCAC")]
    public partial class BulletinTypeLinkedObservations
    {

        private WxObsType[] wxObsField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("WxObs")]
        public WxObsType[] WxObs
        {
            get
            {
                return this.wxObsField;
            }
            set
            {
                this.wxObsField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://caaml.org/Schemas/V5.0/Profiles/BulletinCAC")]
    [System.Xml.Serialization.XmlRootAttribute("WxObs", Namespace = "http://caaml.org/Schemas/V5.0/Profiles/BulletinCAC", IsNullable = false)]
    public partial class WxObsType : AbstractObservationType
    {

        private WxObsTypeWxObsResultsOf wxObsResultsOfField;

        private WxObsTypeLocRef locRefField;

        /// <remarks/>
        public WxObsTypeWxObsResultsOf wxObsResultsOf
        {
            get
            {
                return this.wxObsResultsOfField;
            }
            set
            {
                this.wxObsResultsOfField = value;
            }
        }

        /// <remarks/>
        public WxObsTypeLocRef locRef
        {
            get
            {
                return this.locRefField;
            }
            set
            {
                this.locRefField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://caaml.org/Schemas/V5.0/Profiles/BulletinCAC")]
    public partial class WxObsTypeWxObsResultsOf
    {

        private WxObsMeasurementsType wxObsMeasurementsField;

        /// <remarks/>
        public WxObsMeasurementsType WxObsMeasurements
        {
            get
            {
                return this.wxObsMeasurementsField;
            }
            set
            {
                this.wxObsMeasurementsField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://caaml.org/Schemas/V5.0/Profiles/BulletinCAC")]
    [System.Xml.Serialization.XmlRootAttribute("WxObsMeasurements", Namespace = "http://caaml.org/Schemas/V5.0/Profiles/BulletinCAC", IsNullable = false)]
    public partial class WxObsMeasurementsType : AbstractObsMeasurementsType
    {

        private TempType airTempMinField;

        private TempType airTempMaxField;

        private SnowHeightPointRegularType hN24Field;

        private WxObsMeasurementsTypeHS hsField;

        private WindObsType windField;

        /// <remarks/>
        public TempType airTempMin
        {
            get
            {
                return this.airTempMinField;
            }
            set
            {
                this.airTempMinField = value;
            }
        }

        /// <remarks/>
        public TempType airTempMax
        {
            get
            {
                return this.airTempMaxField;
            }
            set
            {
                this.airTempMaxField = value;
            }
        }

        /// <remarks/>
        public SnowHeightPointRegularType hN24
        {
            get
            {
                return this.hN24Field;
            }
            set
            {
                this.hN24Field = value;
            }
        }

        /// <remarks/>
        public WxObsMeasurementsTypeHS hS
        {
            get
            {
                return this.hsField;
            }
            set
            {
                this.hsField = value;
            }
        }

        /// <remarks/>
        public WindObsType wind
        {
            get
            {
                return this.windField;
            }
            set
            {
                this.windField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://caaml.org/Schemas/V5.0/Profiles/BulletinCAC")]
    public partial class WxObsMeasurementsTypeHS
    {

        private UomLengthMedType uomField;

        private string valueField;

        public WxObsMeasurementsTypeHS()
        {
            this.uomField = UomLengthMedType.cm;
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public UomLengthMedType uom
        {
            get
            {
                return this.uomField;
            }
            set
            {
                this.uomField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://caaml.org/Schemas/V5.0/Profiles/BulletinCAC")]
    public partial class WxObsTypeLocRef : LocRefType
    {
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://caaml.org/Schemas/V5.0/Profiles/BulletinCAC")]
    [System.Xml.Serialization.XmlRootAttribute("Spaw", Namespace = "http://caaml.org/Schemas/V5.0/Profiles/BulletinCAC", IsNullable = false)]
    public partial class SpawType : AbstractObservationType
    {

        private SpawTypeSpawResultsOf spawResultsOfField;

        private SpawTypeLocRef locRefField;

        private SpawTypeLinkedObservations linkedObservationsField;

        /// <remarks/>
        public SpawTypeSpawResultsOf spawResultsOf
        {
            get
            {
                return this.spawResultsOfField;
            }
            set
            {
                this.spawResultsOfField = value;
            }
        }

        /// <remarks/>
        public SpawTypeLocRef locRef
        {
            get
            {
                return this.locRefField;
            }
            set
            {
                this.locRefField = value;
            }
        }

        /// <remarks/>
        public SpawTypeLinkedObservations linkedObservations
        {
            get
            {
                return this.linkedObservationsField;
            }
            set
            {
                this.linkedObservationsField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://caaml.org/Schemas/V5.0/Profiles/BulletinCAC")]
    public partial class SpawTypeSpawResultsOf
    {

        private SpawMeasurementsType spawMeasurementsField;

        /// <remarks/>
        public SpawMeasurementsType SpawMeasurements
        {
            get
            {
                return this.spawMeasurementsField;
            }
            set
            {
                this.spawMeasurementsField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://caaml.org/Schemas/V5.0/Profiles/BulletinCAC")]
    [System.Xml.Serialization.XmlRootAttribute("SpawMeasurements", Namespace = "http://caaml.org/Schemas/V5.0/Profiles/BulletinCAC", IsNullable = false)]
    public partial class SpawMeasurementsType : AbstractObsMeasurementsType
    {

        private string spawTitleField;

        /// <remarks/>
        public string spawTitle
        {
            get
            {
                return this.spawTitleField;
            }
            set
            {
                this.spawTitleField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://caaml.org/Schemas/V5.0/Profiles/BulletinCAC")]
    public partial class SpawTypeLocRef : LocRefType
    {
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://caaml.org/Schemas/V5.0/Profiles/BulletinCAC")]
    public partial class SpawTypeLinkedObservations
    {

        private WxObsType[] wxObsField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("WxObs")]
        public WxObsType[] WxObs
        {
            get
            {
                return this.wxObsField;
            }
            set
            {
                this.wxObsField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://caaml.org/Schemas/V5.0/Profiles/BulletinCAC/Display")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://caaml.org/Schemas/V5.0/Profiles/BulletinCAC/Display", IsNullable = false)]
    public partial class DangerRatingDisplay
    {

        private DangerRatingDisplayMainLabel mainLabelField;

        private DangerRatingDisplayMainForeground mainForegroundField;

        private DangerRatingDisplayMainBackground mainBackgroundField;

        /// <remarks/>
        public DangerRatingDisplayMainLabel mainLabel
        {
            get
            {
                return this.mainLabelField;
            }
            set
            {
                this.mainLabelField = value;
            }
        }

        /// <remarks/>
        public DangerRatingDisplayMainForeground mainForeground
        {
            get
            {
                return this.mainForegroundField;
            }
            set
            {
                this.mainForegroundField = value;
            }
        }

        /// <remarks/>
        public DangerRatingDisplayMainBackground mainBackground
        {
            get
            {
                return this.mainBackgroundField;
            }
            set
            {
                this.mainBackgroundField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://caaml.org/Schemas/V5.0/Profiles/BulletinCAC/Display")]
    public enum DangerRatingDisplayMainLabel
    {

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("n/a")]
        na,

        /// <remarks/>
        Low,

        /// <remarks/>
        Faible,

        /// <remarks/>
        Moderate,

        /// <remarks/>
        Modéré,

        /// <remarks/>
        Considerable,

        /// <remarks/>
        Considérable,

        /// <remarks/>
        High,

        /// <remarks/>
        Élevé,

        /// <remarks/>
        Extreme,

        /// <remarks/>
        Extrême,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://caaml.org/Schemas/V5.0/Profiles/BulletinCAC/Display")]
    public enum DangerRatingDisplayMainForeground
    {

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("000000")]
        Item000000,

        /// <remarks/>
        FFFFFF,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://caaml.org/Schemas/V5.0/Profiles/BulletinCAC/Display")]
    public enum DangerRatingDisplayMainBackground
    {

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("000000")]
        Item000000,

        /// <remarks/>
        FFFFFF,

        /// <remarks/>
        F79218,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("52BA4A")]
        Item52BA4A,

        /// <remarks/>
        EF1C29,

        /// <remarks/>
        FFF300,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://caaml.org/Schemas/V5.0/Profiles/BulletinCAC/Display")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://caaml.org/Schemas/V5.0/Profiles/BulletinCAC/Display", IsNullable = false)]
    public partial class AvProblemDisplay
    {

        private object aspectsBitmapField;

        private string aspectsBitmapURLField;

        private object elevationsBitmapField;

        private string elevationsBitmapURLField;

        private object expectedAvSizeBitmapField;

        private string expectedAvSizeBitmapURLField;

        private object likelihoodOfTriggeringBitmapField;

        private string likelihoodOfTriggeringBitmapURLField;

        /// <remarks/>
        public object aspectsBitmap
        {
            get
            {
                return this.aspectsBitmapField;
            }
            set
            {
                this.aspectsBitmapField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "anyURI")]
        public string aspectsBitmapURL
        {
            get
            {
                return this.aspectsBitmapURLField;
            }
            set
            {
                this.aspectsBitmapURLField = value;
            }
        }

        /// <remarks/>
        public object elevationsBitmap
        {
            get
            {
                return this.elevationsBitmapField;
            }
            set
            {
                this.elevationsBitmapField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "anyURI")]
        public string elevationsBitmapURL
        {
            get
            {
                return this.elevationsBitmapURLField;
            }
            set
            {
                this.elevationsBitmapURLField = value;
            }
        }

        /// <remarks/>
        public object expectedAvSizeBitmap
        {
            get
            {
                return this.expectedAvSizeBitmapField;
            }
            set
            {
                this.expectedAvSizeBitmapField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "anyURI")]
        public string expectedAvSizeBitmapURL
        {
            get
            {
                return this.expectedAvSizeBitmapURLField;
            }
            set
            {
                this.expectedAvSizeBitmapURLField = value;
            }
        }

        /// <remarks/>
        public object likelihoodOfTriggeringBitmap
        {
            get
            {
                return this.likelihoodOfTriggeringBitmapField;
            }
            set
            {
                this.likelihoodOfTriggeringBitmapField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "anyURI")]
        public string likelihoodOfTriggeringBitmapURL
        {
            get
            {
                return this.likelihoodOfTriggeringBitmapURLField;
            }
            set
            {
                this.likelihoodOfTriggeringBitmapURLField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://caaml.org/Schemas/V5.0/Profiles/BulletinCAC/Display")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://caaml.org/Schemas/V5.0/Profiles/BulletinCAC/Display", IsNullable = false)]
    public partial class AspectDisplay
    {

        private AspectDisplayLabel labelField;

        /// <remarks/>
        public AspectDisplayLabel label
        {
            get
            {
                return this.labelField;
            }
            set
            {
                this.labelField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://caaml.org/Schemas/V5.0/Profiles/BulletinCAC/Display")]
    public enum AspectDisplayLabel
    {

        /// <remarks/>
        N,

        /// <remarks/>
        NE,

        /// <remarks/>
        E,

        /// <remarks/>
        SE,

        /// <remarks/>
        S,

        /// <remarks/>
        SW,

        /// <remarks/>
        W,

        /// <remarks/>
        NW,
    }
}
